fruit=[]
f1=input("enter the fruit name:-- ")
fruit.append(f1)
f2=input("enter the fruit name:-- ")
fruit.append(f2)
f3=input("enter the fruit name:-- ")
fruit.append(f3)
f4=input("enter the fruit name:-- ")
fruit.append(f4)
f5=input("enter the fruit name:-- ")
fruit.append(f5)
f6=input("enter the fruit name:-- ")
fruit.append(f6)
f7=input("enter the fruit name:-- ")
fruit.append(f7)
print(fruit)